#line 2 "lex.yy.cpp"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yytext_ptr -= yy_more_len; \
	yyleng = (int) (yy_cp - yytext_ptr); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 40
#define YY_END_OF_BUFFER 41
static yyconst short int yy_acclist[689] =
    {   0,
        1,    1,    8,    8,   41,   39,   40,    1,   39,   40,
        1,   40,   39,   40,   34,   39,   40,   39,   40,   39,
       40,   39,   40,   33,   39,   40,   33,   39,   40,   39,
       40,   39,   40,   39,   40,   32,   39,   40,   32,   39,
       40,   32,   39,   40,   32,   39,   40,   32,   39,   40,
       32,   39,   40,   32,   39,   40,   32,   39,   40,   32,
       39,   40,   32,   39,   40,   32,   39,   40,   32,   39,
       40,    5,   39,   40,    5,   40,    5,   39,   40,    4,
       39,   40,    5,   39,   40,    5,   39,   40,    5,   39,
       40,    5,   33,   39,   40,    5,   33,   39,   40,    5,

       39,   40,    5,   39,   40,    5,   39,   40,    5,   32,
       39,   40,    5,   32,   39,   40,    5,   32,   39,   40,
        5,   32,   39,   40,    5,   32,   39,   40,    5,   32,
       39,   40,    5,   32,   39,   40,    5,   32,   39,   40,
        5,   32,   39,   40,    5,   32,   39,   40,    5,   32,
       39,   40,    5,   32,   39,   40,    8,   39,   40,    8,
       40,    8,   39,   40,    7,   39,   40,    8,   39,   40,
        8,   39,   40,    6,    8,   39,   40,    8,   33,   39,
       40,    8,   33,   39,   40,    8,   39,   40,    8,   39,
       40,    8,   39,   40,    8,   32,   39,   40,    8,   32,

       39,   40,    8,   32,   39,   40,    8,   32,   39,   40,
        8,   32,   39,   40,    8,   32,   39,   40,    8,   32,
       39,   40,    8,   32,   39,   40,    8,   32,   39,   40,
        8,   32,   39,   40,    8,   32,   39,   40,    8,   32,
       39,   40,   35,   39,   40,   36,   40,   35,   39,   40,
       38,   39,   40,   35,   39,   40,   35,   39,   40,   35,
       39,   40,   33,   35,   39,   40,   33,   35,   39,   40,
       35,   39,   40,   35,   39,   40,   35,   39,   40,   32,
       35,   39,   40,   39,   40,   32,   35,   39,   40,   32,
       35,   39,   40,   32,   35,   39,   40,   32,   35,   39,

       40,   32,   35,   39,   40,   32,   35,   39,   40,   32,
       35,   39,   40,   32,   35,   39,   40,   32,   35,   39,
       40,   32,   35,   39,   40,   32,   35,   39,   40,    1,
       14,    9,   17,   10,   18,    3,    2,   33,   33,   11,
       13,   12,   32,   32,   32,   32,   32,   32,   32,   32,
       26,   32,   16,   32,   32,   32,   32,   32,   32,    8,
        8,   14,    8,    9,    8,   17,    8,   10,    8,   18,
        2,    8,    8,   33,    8,    8,   33,    8,   11,    8,
       13,    8,   12,    8,   32,    8,   32,    8,   32,    8,
       32,    8,   32,    8,   32,    8,   32,    8,   32,    8,

       26,   32,    8,   16,   32,    8,   32,    8,   32,    8,
       32,    8,   32,    8,   32,   35,   14,   35,    9,   35,
       17,   35,   10,   35,   18,   35,    3,   35,    2,   35,
       33,   35,   35,   33,   35,   11,   35,   13,   35,   12,
       35,   32,   35,   37,   32,   35,   32,   35,   32,   35,
       32,   35,   32,   35,   32,   35,   32,   35,   26,   32,
       35,   16,   32,   35,   32,   35,   32,   35,   32,   35,
       32,   35,   32,   35,    2,   33,   15,   32,   32,   32,
       32,   32,   32,   24,   32,   32,   22,   32,   32,   32,
       32,    2,    8,    8,   33,    8,   15,   32,    8,   32,

        8,   32,    8,   32,    8,   32,    8,   32,    8,   24,
       32,    8,   32,    8,   22,   32,    8,   32,    8,   32,
        8,   32,    2,   35,   33,   35,   15,   32,   35,   32,
       35,   32,   35,   32,   35,   32,   35,   32,   35,   24,
       32,   35,   32,   35,   22,   32,   35,   32,   35,   32,
       35,   32,   35,   32,   32,   32,   27,   32,   32,   19,
       32,   32,   21,   32,   32,   32,    8,   32,    8,   32,
        8,   32,    8,   27,   32,    8,   32,    8,   19,   32,
        8,   32,    8,   21,   32,    8,   32,    8,   32,   32,
       35,   32,   35,   32,   35,   27,   32,   35,   32,   35,

       19,   32,   35,   32,   35,   21,   32,   35,   32,   35,
       32,   35,   23,   32,   29,   32,   32,   20,   32,   32,
       25,   32,   31,   32,    8,   23,   32,    8,   29,   32,
        8,   32,    8,   20,   32,    8,   32,    8,   25,   32,
        8,   31,   32,   23,   32,   35,   29,   32,   35,   32,
       35,   20,   32,   35,   32,   35,   25,   32,   35,   31,
       32,   35,   32,   30,   32,    8,   32,    8,   30,   32,
       32,   35,   30,   32,   35,   32,    8,   32,   32,   35,
       28,   32,    8,   28,   32,   28,   32,   35
    } ;

static yyconst short int yy_accept[302] =
    {   0,
        1,    2,    3,    3,    3,    4,    5,    5,    5,    6,
        8,   11,   13,   15,   18,   20,   22,   24,   27,   30,
       32,   34,   36,   39,   42,   45,   48,   51,   54,   57,
       60,   63,   66,   69,   72,   75,   77,   80,   83,   86,
       89,   92,   96,  100,  103,  106,  109,  113,  117,  121,
      125,  129,  133,  137,  141,  145,  149,  153,  157,  160,
      162,  165,  168,  171,  174,  178,  182,  186,  189,  192,
      195,  199,  203,  207,  211,  215,  219,  223,  227,  231,
      235,  239,  243,  246,  248,  251,  254,  257,  260,  263,
      267,  271,  274,  277,  280,  284,  286,  290,  294,  298,

      302,  306,  310,  314,  318,  322,  326,  330,  331,  332,
      333,  334,  335,  336,  337,  338,  339,  339,  340,  341,
      342,  343,  344,  345,  346,  347,  348,  349,  350,  351,
      353,  355,  356,  357,  358,  359,  360,  361,  363,  365,
      367,  369,  371,  373,  375,  376,  378,  380,  382,  384,
      386,  388,  390,  392,  394,  396,  398,  400,  403,  406,
      408,  410,  412,  414,  416,  417,  419,  421,  423,  425,
      427,  429,  431,  433,  434,  436,  438,  440,  442,  444,
      445,  447,  449,  451,  453,  455,  457,  459,  462,  465,
      467,  469,  471,  473,  475,  476,  477,  479,  480,  481,

      482,  483,  484,  486,  487,  489,  490,  491,  492,  494,
      496,  499,  501,  503,  505,  507,  509,  512,  514,  517,
      519,  521,  523,  525,  527,  530,  532,  534,  536,  538,
      540,  543,  545,  548,  550,  552,  554,  555,  556,  557,
      559,  560,  562,  563,  565,  566,  567,  569,  571,  573,
      576,  578,  581,  583,  586,  588,  590,  592,  594,  596,
      599,  601,  604,  606,  609,  611,  613,  615,  617,  618,
      620,  621,  623,  625,  628,  631,  633,  636,  638,  641,
      644,  647,  650,  652,  655,  657,  660,  663,  664,  666,
      668,  671,  673,  676,  677,  679,  681,  683,  686,  689,

      689
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    1,    1,    1,    1,
        1,    6,    7,    1,    8,    1,    9,   10,   11,   11,
       11,   11,   11,   11,   11,   12,   12,    1,    1,   13,
       14,   15,    1,    1,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
        1,   17,    1,    1,   18,    1,   19,   20,   21,   22,

       23,   24,   16,   25,   26,   16,   27,   28,   16,   29,
       30,   16,   16,   31,   32,   33,   34,   35,   36,   37,
       38,   16,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[39] =
    {   0,
        1,    1,    2,    1,    3,    4,    1,    1,    1,    5,
        5,    5,    1,    1,    1,    5,    3,    6,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5
    } ;

static yyconst short int yy_base[312] =
    {   0,
        0,    0,   38,    0,   76,    0,  114,    0,  754,  755,
      151,  153,  739,  755,  150,  151,  152,  152,  156,  738,
      737,  736,    0,  140,  718,  718,  719,  148,  722,  714,
      721,  153,  718,  716,  755,  755,  727,  755,  166,  168,
      168,  173,  175,  726,  725,  724,    0,  150,  706,  706,
      707,  166,  710,  699,  706,  171,  698,  693,    0,    0,
      691,  755,  184,  186,  186,  191,  193,  686,  685,  680,
      228,  245,  168,  177,  183,  187,  191,  190,  232,  246,
      209,  238,    0,  755,  679,  755,  237,  258,  217,  246,
      268,  675,  669,  662,  283,  655,  298,  196,  264,  242,

      279,  257,  285,  292,  303,  295,  302,  315,  755,  755,
      755,  755,  755,  755,    0,  325,    0,  327,  755,  755,
      755,    0,  603,  573,  577,  568,  562,  543,  532,    0,
        0,  519,  520,  524,  508,  510,    0,    0,    0,    0,
        0,    0,  337,  331,  343,  343,    0,    0,    0,  333,
      337,  334,  344,  340,  345,  349,  350,  353,  354,  357,
      358,  368,  367,  371,    0,    0,    0,    0,    0,    0,
        0,  387,  395,  406,  406,    0,    0,    0,  372,  755,
      400,  380,  403,  394,  404,  414,  399,  409,  410,  413,
      418,  425,  424,  428,    0,    0,    0,  510,  497,  479,

      475,  437,    0,  459,    0,  445,  434,  424,  457,  463,
      444,  455,  460,  454,  459,  471,  465,  470,  474,  482,
      479,  486,  492,  517,  491,  508,  509,  512,  513,  525,
      519,  524,  528,  536,  533,  540,  389,  368,  344,    0,
      321,    0,  299,    0,  296,  281,  541,  546,  552,  545,
      556,  551,  557,  560,  567,  570,  564,  576,  580,  579,
      584,  585,  588,  589,  598,  601,    0,    0,  253,    0,
      210,    0,    0,  593,  597,  602,  605,  606,  609,  610,
      613,  614,  617,  618,  621,  622,  625,  190,    0,  626,
      630,  633,  634,  190,  643,  646,    0,  639,  642,  755,

      673,  679,  685,  691,  697,  703,  155,  709,  715,  721,
      727
    } ;

static yyconst short int yy_def[312] =
    {   0,
      300,    1,  300,    3,  300,    5,  300,    7,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  302,  302,
      302,  300,  302,  302,  302,  302,  302,  302,  302,  302,
      303,  303,   72,   72,   72,   72,   72,   72,   72,   72,
       72,   72,  304,  300,  304,  300,  304,  304,  304,  304,
      304,  304,  304,  304,  305,  300,  305,   97,   97,   97,

       97,   97,   97,   97,   97,   97,   97,  300,  300,  300,
      300,  300,  300,  300,  306,  300,  307,  300,  300,  300,
      300,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  302,  302,  302,  302,
      302,  302,  308,  302,  309,  302,  302,  302,  302,   72,
       72,   72,   72,   72,   72,   72,   72,   72,   72,   72,
       72,   72,   72,   72,  304,  304,  304,  304,  304,  304,
      304,  310,  304,  311,  304,  304,  304,  304,   97,  300,
       97,   97,   97,   97,   97,   97,   97,   97,   97,   97,
       97,   97,   97,   97,  306,  307,  301,  301,  301,  301,

      301,  301,  301,  301,  301,  301,  301,  301,  308,  309,
       72,   72,   72,   72,   72,   72,   72,   72,   72,   72,
       72,   72,  310,  311,   97,   97,   97,   97,   97,   97,
       97,   97,   97,   97,   97,   97,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,   72,   72,   72,   72,
       72,   72,   72,   72,   72,   72,   97,   97,   97,   97,
       97,   97,   97,   97,   97,   97,  301,  301,  301,  301,
      301,  301,  301,   72,   72,   72,   72,   72,   72,   72,
       97,   97,   97,   97,   97,   97,   97,  301,  301,   72,
       72,   97,   97,  301,   72,   97,  301,   72,   97,    0,

      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300
    } ;

static yyconst short int yy_nxt[794] =
    {   0,
       10,   11,   12,   13,   14,   10,   15,   16,   17,   18,
       19,   19,   20,   21,   22,   23,   10,   23,   24,   25,
       26,   23,   27,   28,   23,   29,   23,   23,   23,   30,
       31,   23,   23,   23,   32,   33,   23,   34,   35,   35,
       36,   37,   35,   38,   39,   40,   41,   42,   43,   43,
       44,   45,   46,   47,   35,   47,   48,   49,   50,   47,
       51,   52,   47,   53,   47,   47,   47,   54,   55,   47,
       47,   47,   56,   57,   47,   58,   59,   59,   60,   61,
       59,   62,   63,   64,   65,   66,   67,   67,   68,   69,
       70,   71,   59,   71,   72,   73,   74,   71,   75,   76,

       71,   77,   71,   71,   71,   78,   79,   71,   71,   71,
       80,   81,   71,   82,   83,   83,   84,   85,   86,   83,
       87,   88,   89,   90,   91,   91,   92,   93,   94,   95,
       96,   95,   97,   98,   99,   95,  100,  101,   95,  102,
       95,   95,   95,  103,  104,   95,   95,   95,  105,  106,
       95,  107,  108,  108,  108,  108,  110,  114,  112,  196,
      115,  116,  116,  111,  113,  118,  118,  118,  123,  128,
      124,  133,  110,  114,  134,  112,  115,  129,  123,  111,
      124,  113,  116,  116,  118,  118,  118,  128,  117,  133,
      139,  114,  134,  141,  143,  129,  150,  140,  153,  142,

      144,  144,  146,  146,  146,  150,  154,  150,  156,  117,
      155,  150,  297,  150,  158,  150,  157,  150,  150,  150,
      159,  150,  171,  294,  179,  172,  183,  145,  137,  137,
      137,  137,  137,  163,  137,  137,  137,  150,  289,  150,
      137,  137,  137,  167,  137,  137,  137,  137,  137,  137,
      168,  137,  137,  137,  160,  173,  173,  137,  137,  137,
      150,  137,  150,  164,  161,  169,  150,  162,  150,  185,
      179,  170,  179,  151,  150,  152,  150,  175,  175,  175,
      188,  288,  174,  165,  165,  179,  165,  179,  165,  165,
      165,  165,  179,  184,  179,  165,  165,  165,  165,  165,

      186,  165,  273,  165,  165,  165,  165,  179,  187,  179,
      165,  165,  165,  179,  190,  189,  108,  108,  272,  193,
      179,  191,  179,  179,  192,  179,  181,  194,  182,  271,
      179,  179,  179,  179,  116,  116,  118,  118,  118,  137,
      144,  144,  195,  137,  137,  137,  137,  137,  270,  137,
      137,  137,  146,  146,  146,  137,  137,  137,  211,  137,
      137,  150,  150,  150,  212,  150,  213,  150,  214,  269,
      150,  216,  150,  150,  150,  150,  215,  150,  150,  150,
      217,  150,  150,  150,  150,  150,  150,  150,  219,  218,
      220,  195,  221,  222,  268,  150,  150,  150,  150,  150,

      179,  150,  179,  195,  173,  173,  165,  165,  179,  165,
      226,  165,  165,  165,  165,  175,  175,  175,  165,  165,
      165,  225,  228,  165,  179,  227,  267,  179,  179,  231,
      179,  179,  179,  179,  179,  229,  230,  179,  179,  179,
      179,  179,  179,  179,  179,  232,  179,  234,  233,  235,
      236,  246,  179,  179,  179,  179,  179,  241,  179,  137,
      242,  245,  195,  137,  137,  137,  137,  137,  244,  137,
      137,  137,  150,  247,  150,  137,  137,  137,  248,  137,
      137,  250,  150,  150,  150,  150,  249,  150,  150,  150,
      150,  251,  243,  150,  252,  150,  195,  240,  150,  150,

      150,  150,  150,  253,  150,  254,  255,  150,  195,  150,
      150,  239,  150,  256,  150,  238,  150,  165,  165,  179,
      165,  179,  165,  165,  165,  165,  257,  258,  237,  165,
      165,  165,  208,  207,  165,  260,  179,  179,  179,  179,
      179,  179,  179,  179,  259,  261,  206,  179,  262,  179,
      205,  204,  179,  179,  179,  179,  179,  263,  179,  264,
      265,  179,  203,  179,  179,  202,  179,  266,  179,  150,
      179,  150,  275,  150,  150,  150,  150,  276,  274,  150,
      150,  150,  150,  277,  150,  150,  150,  278,  150,  279,
      150,  280,  179,  201,  179,  150,  200,  150,  150,  199,

      150,  281,  282,  198,  179,  283,  179,  179,  179,  179,
      179,  284,  179,  179,  179,  179,  179,  179,  285,  179,
      286,  150,  287,  150,  197,  150,  179,  150,  179,  179,
      290,  179,  150,  150,  291,  150,  150,  150,  150,  150,
      150,  179,  179,  179,  179,  292,  179,  179,  179,  293,
      179,  179,  179,  179,  150,  179,  150,  180,  150,  295,
      150,  179,  179,  179,  179,  298,  296,  150,  299,  150,
      179,  150,  179,  150,  179,  178,  179,  122,  122,  137,
      137,  137,  177,  137,  137,  150,  150,  150,  176,  150,
      150,  165,  166,  149,  165,  165,  165,  179,  148,  147,

      179,  179,  179,  195,  138,  195,  195,  195,  195,  209,
      209,  209,  209,  209,  209,  210,  210,  210,  136,  210,
      210,  223,  135,  223,  223,  223,  223,  224,  132,  131,
      224,  224,  224,  130,  127,  126,  125,  121,  120,  119,
      109,  136,  135,  132,  131,  130,  127,  126,  125,  121,
      120,  119,  109,  300,    9,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300

    } ;

static yyconst short int yy_chk[794] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,

        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,   11,   11,   12,   12,   15,   17,   16,  307,
       17,   18,   18,   15,   16,   19,   19,   19,   24,   28,
       24,   32,   39,   41,   32,   40,   41,   28,   48,   39,
       48,   40,   42,   42,   43,   43,   43,   52,   18,   56,
       63,   65,   56,   64,   65,   52,   73,   63,   73,   64,

       66,   66,   67,   67,   67,   74,   74,   74,   76,   42,
       75,   75,  294,   75,   77,   76,   76,   76,   78,   77,
       78,   77,   89,  288,   98,   89,   98,   66,   71,   71,
       71,   71,   71,   81,   71,   71,   71,   81,  271,   81,
       71,   71,   71,   87,   71,   72,   72,   72,   72,   72,
       87,   72,   72,   72,   79,   90,   90,   72,   72,   72,
       79,   72,   79,   82,   80,   88,   82,   80,   82,  100,
      100,   88,  100,   72,   80,   72,   80,   91,   91,   91,
      102,  269,   90,   95,   95,  102,   95,  102,   95,   95,
       95,   95,   99,   99,   99,   95,   95,   95,   97,   97,

      101,   97,  246,   97,   97,   97,   97,  101,  101,  101,
       97,   97,   97,  103,  104,  103,  108,  108,  245,  106,
      104,  105,  104,  106,  105,  106,   97,  107,   97,  243,
      107,  105,  107,  105,  116,  116,  118,  118,  118,  143,
      144,  144,  143,  145,  145,  145,  145,  145,  241,  145,
      145,  145,  146,  146,  146,  145,  145,  145,  151,  145,
      145,  150,  152,  150,  152,  151,  153,  151,  154,  239,
      154,  156,  153,  155,  153,  155,  155,  156,  157,  156,
      157,  158,  159,  158,  159,  160,  161,  160,  161,  160,
      162,  172,  163,  164,  238,  163,  162,  163,  162,  164,

      179,  164,  179,  172,  173,  173,  174,  174,  182,  174,
      182,  174,  174,  174,  174,  175,  175,  175,  174,  174,
      174,  181,  184,  174,  184,  183,  237,  187,  181,  187,
      181,  183,  185,  183,  185,  185,  186,  188,  189,  188,
      189,  190,  186,  190,  186,  190,  191,  192,  191,  193,
      194,  208,  193,  192,  193,  192,  194,  202,  194,  209,
      202,  207,  209,  210,  210,  210,  210,  210,  206,  210,
      210,  210,  211,  212,  211,  210,  210,  210,  213,  210,
      210,  215,  214,  212,  214,  212,  214,  215,  213,  215,
      213,  216,  204,  217,  216,  217,  223,  201,  218,  216,

      218,  216,  219,  218,  219,  220,  221,  221,  223,  221,
      220,  200,  220,  222,  222,  199,  222,  224,  224,  225,
      224,  225,  224,  224,  224,  224,  226,  227,  198,  224,
      224,  224,  136,  135,  224,  229,  226,  227,  226,  227,
      228,  229,  228,  229,  228,  230,  134,  231,  230,  231,
      133,  132,  232,  230,  232,  230,  233,  232,  233,  234,
      235,  235,  129,  235,  234,  128,  234,  236,  236,  247,
      236,  247,  248,  250,  248,  250,  248,  249,  247,  252,
      249,  252,  249,  251,  251,  253,  251,  253,  254,  255,
      254,  256,  257,  127,  257,  255,  126,  255,  256,  125,

      256,  257,  258,  124,  258,  259,  258,  260,  259,  260,
      259,  261,  261,  262,  261,  262,  263,  264,  263,  264,
      265,  274,  266,  274,  123,  275,  265,  275,  265,  266,
      276,  266,  276,  277,  278,  277,  278,  279,  280,  279,
      280,  281,  282,  281,  282,  283,  284,  283,  284,  285,
      286,  285,  286,  287,  290,  287,  290,   96,  291,  290,
      291,  292,  293,  292,  293,  295,  292,  298,  296,  298,
      299,  295,  299,  295,  296,   94,  296,  301,  301,  302,
      302,  302,   93,  302,  302,  303,  303,  303,   92,  303,
      303,  304,   85,   70,  304,  304,  304,  305,   69,   68,

      305,  305,  305,  306,   61,  306,  306,  306,  306,  308,
      308,  308,  308,  308,  308,  309,  309,  309,   58,  309,
      309,  310,   57,  310,  310,  310,  310,  311,   55,   54,
      311,  311,  311,   53,   51,   50,   49,   46,   45,   44,
       37,   34,   33,   31,   30,   29,   27,   26,   25,   22,
       21,   20,   13,    9,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300

    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
static int yy_more_flag = 0;
static int yy_more_len = 0;
#define yymore() (yy_more_flag = 1)
#define YY_MORE_ADJ yy_more_len
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "eudc.l"
#define INITIAL 0
#line 2 "eudc.l"
#include "eudc.tab.hpp"
#include <stdlib.h>
#include "ast.h"

void yyerror(char *);
   
#define YY_NO_UNISTD_H
#define YY_NEVER_INTERACTIVE 1

#define STATE_LC 1
#define STATE_LC2 2

#define STATE_STRING 3

#line 749 "lex.yy.cpp"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 20 "eudc.l"

	/*
	%token NAME INTEGER STRING
	%token INCR DECR LE GE EQ NE AND OR ADDMOV SUBMOV
	%token FDEF FDECL VDEF VAR ARRAY
	%token FOR WHILE IF ELSE CONTINUE BREAK
	%token RETURN YIELD
	*/



	/* Ignore blank line & comments */
#line 913 "lex.yy.cpp"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_more_len = 0;
		if ( yy_more_flag )
			{
			yy_more_len = yy_c_buf_p - yytext_ptr;
			yy_more_flag = 0;
			}
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 301 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 755 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 32 "eudc.l"
;
	YY_BREAK
/* Ignore comment */
case 2:
YY_RULE_SETUP
#line 35 "eudc.l"
{}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 36 "eudc.l"
{ BEGIN STATE_LC; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 37 "eudc.l"
{ BEGIN STATE_LC2; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 38 "eudc.l"
{ }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 39 "eudc.l"
{ BEGIN 0; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 40 "eudc.l"
{}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 41 "eudc.l"
{ BEGIN STATE_LC; }
	YY_BREAK
/* Read all known keywords
	 LE GE EQ NE AND OR ADDMOV SUBMOV
	 FDEF FDECL VDEF VAR ARR
	 FOR WHILE IF ELSE CONTINUE BREAK
	 RETURN YIELD
	*/
case 9:
YY_RULE_SETUP
#line 52 "eudc.l"
{ return INCR; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 53 "eudc.l"
{ return DECR; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 54 "eudc.l"
{ return LE; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 55 "eudc.l"
{ return GE; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 56 "eudc.l"
{ return EQ; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 57 "eudc.l"
{ return NE; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 58 "eudc.l"
{ return AND; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 59 "eudc.l"
{ return OR; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 60 "eudc.l"
{ return ADDMOV; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 61 "eudc.l"
{ return SUBMOV; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 63 "eudc.l"
{ return FDEF; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 64 "eudc.l"
{ return FDECL; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 66 "eudc.l"
{ return VDEF; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 67 "eudc.l"
{ return VAR; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 68 "eudc.l"
{ return ARRAY; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 70 "eudc.l"
{ return FOR; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 71 "eudc.l"
{ return WHILE; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 72 "eudc.l"
{ return IF; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 73 "eudc.l"
{ return ELSE; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 74 "eudc.l"
{ return CONTINUE; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 75 "eudc.l"
{ return BREAK; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 76 "eudc.l"
{ return RETURN; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 77 "eudc.l"
{ return YIELD; }
	YY_BREAK
/* Read identifiers */
case 32:
YY_RULE_SETUP
#line 81 "eudc.l"
{
		yylval = makenode("name", yytext);
		return NAME;
	}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 86 "eudc.l"
{
		yylval = makenode("integer", yytext);
		return INTEGER;
	}
	YY_BREAK
/* String */
case 34:
YY_RULE_SETUP
#line 93 "eudc.l"
{
	BEGIN STATE_STRING;
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 97 "eudc.l"
{
	yymore();
}
	YY_BREAK
case YY_STATE_EOF(STATE_STRING):
#line 101 "eudc.l"
{
	yyerror("EOF in string.");
	BEGIN 0;
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 106 "eudc.l"
{
	yyerror("Unterminated string.");
	BEGIN 0;
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 111 "eudc.l"
{
	// Ignore
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 115 "eudc.l"
{
	yytext[yyleng-1] = '\0';
	BEGIN 0;
	yylval = makenode("string", yytext);
	return STRING;
}
	YY_BREAK
/* anything else will just pass by. */
case 39:
YY_RULE_SETUP
#line 124 "eudc.l"
{ return *yytext; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 126 "eudc.l"
ECHO;
	YY_BREAK
#line 1247 "lex.yy.cpp"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(STATE_LC):
			case YY_STATE_EOF(STATE_LC2):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 301 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 301 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 300);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 126 "eudc.l"
