#line 2 "lex.yy.cpp"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yytext_ptr -= yy_more_len; \
	yyleng = (int) (yy_cp - yytext_ptr); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 47
#define YY_END_OF_BUFFER 48
static yyconst short int yy_acclist[681] =
    {   0,
        1,    1,    8,    8,   48,   46,   47,    1,   46,   47,
        1,   47,   46,   47,   41,   46,   47,   46,   47,   46,
       47,   46,   47,   46,   47,   46,   47,   46,   47,   40,
       46,   47,   40,   46,   47,   46,   47,   46,   47,   46,
       47,   39,   46,   47,   46,   47,   39,   46,   47,   39,
       46,   47,   39,   46,   47,   39,   46,   47,   39,   46,
       47,   39,   46,   47,   39,   46,   47,   39,   46,   47,
       39,   46,   47,   46,   47,    5,   46,   47,    5,   47,
        5,   46,   47,    5,   46,   47,    5,   46,   47,    4,
       46,   47,    5,   46,   47,    5,   46,   47,    5,   46,

       47,    5,   40,   46,   47,    5,   40,   46,   47,    5,
       46,   47,    5,   46,   47,    5,   46,   47,    5,   39,
       46,   47,    5,   46,   47,    5,   39,   46,   47,    5,
       39,   46,   47,    5,   39,   46,   47,    5,   39,   46,
       47,    5,   39,   46,   47,    5,   39,   46,   47,    5,
       39,   46,   47,    5,   39,   46,   47,    5,   39,   46,
       47,    5,   46,   47,    8,   46,   47,    8,   47,    8,
       46,   47,    8,   46,   47,    8,   46,   47,    7,   46,
       47,    8,   46,   47,    8,   46,   47,    6,    8,   46,
       47,    8,   40,   46,   47,    8,   40,   46,   47,    8,

       46,   47,    8,   46,   47,    8,   46,   47,    8,   39,
       46,   47,    8,   46,   47,    8,   39,   46,   47,    8,
       39,   46,   47,    8,   39,   46,   47,    8,   39,   46,
       47,    8,   39,   46,   47,    8,   39,   46,   47,    8,
       39,   46,   47,    8,   39,   46,   47,    8,   39,   46,
       47,    8,   46,   47,   42,   46,   47,   43,   47,   42,
       46,   47,   45,   46,   47,   42,   46,   47,   42,   46,
       47,   42,   46,   47,   42,   46,   47,   42,   46,   47,
       42,   46,   47,   40,   42,   46,   47,   40,   42,   46,
       47,   42,   46,   47,   42,   46,   47,   42,   46,   47,

       39,   42,   46,   47,   46,   47,   42,   46,   47,   39,
       42,   46,   47,   39,   42,   46,   47,   39,   42,   46,
       47,   39,   42,   46,   47,   39,   42,   46,   47,   39,
       42,   46,   47,   39,   42,   46,   47,   39,   42,   46,
       47,   39,   42,   46,   47,   42,   46,   47,    1,   24,
       31,   25,   32,   29,   17,   27,   18,   28,    3,    2,
       30,   40,   40,   19,   21,   23,   22,   20,   39,   34,
       39,   39,   39,   39,   39,    9,   39,   39,   39,   39,
       39,   33,   26,    8,    8,   24,    8,   31,    8,   25,
        8,   32,    8,   17,    8,   27,    8,   18,    8,   28,

        2,    8,    8,   30,    8,   40,    8,    8,   40,    8,
       19,    8,   21,    8,   23,    8,   22,    8,   20,    8,
       39,    8,   34,    8,   39,    8,   39,    8,   39,    8,
       39,    8,   39,    8,    9,   39,    8,   39,    8,   39,
        8,   39,    8,   39,    8,   33,    8,   26,   42,   24,
       42,   31,   42,   25,   42,   32,   42,   29,   42,   17,
       42,   27,   42,   18,   42,   28,   42,    3,   42,    2,
       42,   30,   42,   40,   42,   42,   40,   42,   19,   42,
       21,   42,   23,   42,   22,   42,   20,   42,   39,   42,
       44,   34,   42,   39,   42,   39,   42,   39,   42,   39,

       42,   39,   42,    9,   39,   42,   39,   42,   39,   42,
       39,   42,   39,   42,   33,   42,   26,   42,    2,   40,
       35,   36,   39,   39,   39,   11,   39,   39,   38,   39,
       39,   37,   39,   39,    2,    8,    8,   40,    8,   35,
        8,   36,    8,   39,    8,   39,    8,   39,    8,   11,
       39,    8,   39,    8,   38,   39,    8,   39,    8,   37,
       39,    8,   39,    2,   42,   40,   42,   35,   42,   36,
       42,   39,   42,   39,   42,   39,   42,   11,   39,   42,
       39,   42,   38,   39,   42,   39,   42,   37,   39,   42,
       39,   42,   39,   39,   10,   39,   13,   39,   39,   39,

        8,   39,    8,   39,    8,   10,   39,    8,   13,   39,
        8,   39,    8,   39,   39,   42,   39,   42,   10,   39,
       42,   13,   39,   42,   39,   42,   39,   42,   15,   39,
       39,   39,   12,   39,    8,   15,   39,    8,   39,    8,
       39,    8,   12,   39,   15,   39,   42,   39,   42,   39,
       42,   12,   39,   42,   39,   16,   39,    8,   39,    8,
       16,   39,   39,   42,   16,   39,   42,   39,    8,   39,
       39,   42,   14,   39,    8,   14,   39,   14,   39,   42
    } ;

static yyconst short int yy_accept[305] =
    {   0,
        1,    2,    3,    3,    3,    4,    5,    5,    5,    6,
        8,   11,   13,   15,   18,   20,   22,   24,   26,   28,
       30,   33,   36,   38,   40,   42,   45,   47,   50,   53,
       56,   59,   62,   65,   68,   71,   74,   76,   79,   81,
       84,   87,   90,   93,   96,   99,  102,  106,  110,  113,
      116,  119,  123,  126,  130,  134,  138,  142,  146,  150,
      154,  158,  162,  165,  168,  170,  173,  176,  179,  182,
      185,  188,  192,  196,  200,  203,  206,  209,  213,  216,
      220,  224,  228,  232,  236,  240,  244,  248,  252,  255,
      258,  260,  263,  266,  269,  272,  275,  278,  281,  284,

      288,  292,  295,  298,  301,  305,  307,  310,  314,  318,
      322,  326,  330,  334,  338,  342,  346,  349,  350,  351,
      352,  353,  354,  355,  356,  357,  358,  359,  360,  361,
      362,  363,  363,  364,  365,  366,  367,  368,  369,  370,
      371,  372,  373,  374,  375,  376,  378,  379,  380,  381,
      382,  383,  384,  385,  387,  389,  391,  393,  395,  397,
      399,  401,  403,  405,  407,  408,  410,  412,  414,  416,
      418,  420,  422,  424,  426,  428,  430,  432,  434,  437,
      439,  441,  443,  445,  447,  449,  450,  452,  454,  456,
      458,  460,  462,  464,  466,  468,  470,  472,  474,  476,

      477,  479,  481,  483,  485,  487,  489,  491,  492,  494,
      496,  498,  500,  502,  504,  507,  509,  511,  513,  515,
      517,  519,  520,  521,  522,  523,  524,  525,  526,  528,
      529,  531,  532,  534,  535,  537,  539,  541,  543,  545,
      547,  549,  552,  554,  557,  559,  562,  564,  566,  568,
      570,  572,  574,  576,  578,  581,  583,  586,  588,  591,
      593,  594,  595,  597,  599,  600,  601,  603,  605,  608,
      611,  613,  615,  617,  619,  622,  625,  627,  629,  631,
      632,  633,  635,  638,  640,  642,  645,  648,  650,  652,
      655,  656,  658,  660,  663,  665,  668,  669,  671,  673,

      675,  678,  681,  681
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    7,    1,    1,
        1,    8,    9,    1,   10,    1,   11,   12,   13,   13,
       13,   13,   13,   13,   13,   14,   14,    1,    1,   15,
       16,   17,    1,    1,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
        1,   19,    1,   20,   21,    1,   22,   23,   24,   18,

       25,   26,   18,   27,   28,   18,   29,   30,   18,   31,
       32,   33,   18,   34,   35,   36,   37,   38,   39,   40,
       18,   18,    1,   41,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[42] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    4,    1,    1,
        1,    5,    5,    5,    1,    1,    1,    5,    3,    1,
        6,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        1
    } ;

static yyconst short int yy_base[314] =
    {   0,
        0,    0,   41,    0,   82,    0,  123,    0,  661,  662,
      163,  165,  644,  662,  643,  162,  642,  161,  163,  164,
      169,  171,  171,  641,  172,    0,  640,  621,  622,  623,
      139,  626,  615,  625,  627,  621,  158,  662,  662,  631,
      630,  184,  629,  181,  182,  185,  182,  190,  190,  628,
      191,    0,  627,  608,  609,  610,  178,  613,  602,  612,
      614,  608,  195,    0,    0,  618,  617,  205,  616,  204,
      207,  208,  213,  215,  215,  615,  216,  253,  614,  294,
      203,  184,  206,  208,  205,  227,  243,  217,  230,    0,
      662,  613,  662,  612,  259,  611,  258,  266,  270,  267,

      235,  268,  610,  271,  335,  622,  608,  376,  257,  272,
      283,  259,  256,  287,  296,  289,  292,  322,  662,  662,
      662,  662,  662,  662,  662,  662,  662,  662,    0,  662,
      314,    0,  335,  607,  662,  662,  662,  606,    0,  662,
      596,  589,  584,  584,  586,    0,  582,  579,  580,  585,
      662,  662,    0,    0,    0,    0,    0,    0,    0,    0,
        0,  242,    0,  319,  417,  344,  596,    0,    0,    0,
      595,  576,    0,  304,  288,  319,  575,  328,  574,  573,
      327,  572,  306,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  355,    0,  352,  458,

      354,  589,    0,    0,    0,  588,  569,  662,    0,  345,
      338,  354,  568,  363,  567,  566,  337,  565,  347,    0,
        0,    0,    0,  662,  662,  576,  561,  571,    0,  571,
        0,  557,    0,  563,  387,    0,    0,    0,  377,  364,
      378,  558,  380,  557,  368,  553,  379,  396,  499,    0,
        0,  448,  372,  382,  552,  437,  546,  443,  534,  442,
      534,  534,    0,    0,  523,  531,  452,  455,  518,  512,
      505,  459,  456,  460,  504,  503,  502,  462,    0,  504,
      503,    0,  499,  461,  487,  498,  496,  491,  492,  495,
      480,    0,  490,  478,  494,  464,  472,  477,  479,    0,

      457,  429,  662,  536,  542,  548,  554,  560,  566,  420,
      572,  578,  584
    } ;

static yyconst short int yy_def[314] =
    {   0,
      303,    1,  303,    3,  303,    5,  303,    7,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  304,  303,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  304,  303,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  303,  305,  305,  305,  305,  305,  303,  305,
      305,  305,  305,  305,  305,  305,  305,  306,  305,  306,
       80,   80,   80,   80,   80,   80,   80,   80,  305,  307,
      303,  307,  303,  307,  307,  307,  307,  307,  307,  307,

      307,  307,  307,  307,  308,  303,  307,  308,  108,  108,
      108,  108,  108,  108,  108,  108,  307,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  309,  303,
      303,  310,  303,  303,  303,  303,  303,  303,  304,  303,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      303,  303,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  311,  305,  305,  303,  305,  305,  305,  305,  305,
      305,   80,  305,   80,   80,   80,   80,   80,   80,   80,
       80,   80,   80,  305,  305,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  312,  307,  307,  313,

      307,  307,  307,  307,  307,  307,  108,  303,  307,  108,
      108,  108,  108,  108,  108,  108,  108,  108,  108,  307,
      307,  309,  310,  303,  303,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  311,  165,  305,  305,   80,   80,
       80,   80,   80,   80,   80,   80,   80,  312,  313,  307,
      307,  108,  108,  108,  108,  108,  108,  108,  108,  108,
      304,  304,  304,  304,  304,  304,   80,   80,   80,   80,
       80,   80,  108,  108,  108,  108,  108,  108,  304,  304,
      304,  304,   80,   80,   80,   80,  108,  108,  108,  108,
      304,  304,   80,   80,  108,  108,  304,   80,  108,  304,

       80,  108,    0,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303
    } ;

static yyconst short int yy_nxt[704] =
    {   0,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   22,   23,   24,   25,   26,   10,   27,
       26,   26,   28,   29,   30,   31,   26,   32,   26,   26,
       26,   26,   33,   34,   26,   26,   26,   35,   36,   26,
       37,   38,   38,   39,   40,   38,   41,   42,   43,   44,
       45,   46,   47,   48,   48,   49,   50,   51,   52,   38,
       53,   52,   52,   54,   55,   56,   57,   52,   58,   52,
       52,   52,   52,   59,   60,   52,   52,   52,   61,   62,
       52,   63,   64,   64,   65,   66,   64,   67,   68,   69,
       70,   71,   72,   73,   74,   74,   75,   76,   77,   78,

       64,   79,   78,   78,   80,   81,   82,   83,   78,   84,
       78,   78,   78,   78,   85,   86,   78,   78,   78,   87,
       88,   78,   89,   90,   90,   91,   92,   93,   94,   95,
       96,   97,   98,   99,  100,  101,  101,  102,  103,  104,
      105,  106,  107,  105,  105,  108,  109,  110,  111,  105,
      112,  105,  105,  105,  105,  113,  114,  105,  105,  105,
      115,  116,  105,  117,  118,  118,  118,  118,  121,  124,
      144,  128,  126,  151,  129,  145,  125,  122,  127,  130,
      131,  131,  133,  133,  133,  134,  135,  137,  138,  124,
      121,  126,  128,  131,  131,  129,  125,  127,  152,  122,

      130,  133,  133,  133,  134,  135,  137,  138,  132,  144,
      151,  156,  158,  176,  145,  128,  160,  172,  162,  159,
      157,  132,  161,  163,  164,  164,  166,  166,  166,  167,
      168,  170,  171,  179,  175,  152,  172,  177,  172,  172,
      180,  172,  178,  183,  153,  184,  201,  201,  201,  222,
      172,  181,  165,  153,  153,  153,  153,  153,  153,  153,
      172,  153,  153,  153,  182,  189,  192,  153,  153,  153,
      185,  153,  153,  193,  190,  194,  172,  196,  199,  199,
      197,  195,  202,  203,  215,  198,  205,  206,  211,  207,
      207,  216,  207,  153,  153,  153,  153,  153,  153,  153,

      153,  212,  153,  153,  153,  207,  200,  220,  153,  153,
      153,  217,  153,  153,  213,  219,  207,  218,  240,  214,
      207,  172,  207,  118,  118,  131,  131,  174,  239,  207,
      164,  164,  221,  247,  153,  186,  186,  172,  186,  172,
      186,  186,  186,  186,  186,  186,  133,  133,  133,  186,
      186,  186,  172,  241,  186,  166,  166,  166,  243,  222,
      172,  172,  245,  199,  199,  201,  201,  201,  253,  252,
      207,  207,  258,  222,  260,  186,  186,  186,  207,  186,
      207,  186,  186,  186,  186,  186,  186,  207,  254,  153,
      186,  186,  186,  256,  222,  186,  207,  172,  267,  268,

      222,  172,  269,  270,  271,  207,  275,  274,  272,  210,
      172,  172,  172,  172,  222,  207,  186,  153,  153,  153,
      153,  153,  153,  153,  223,  153,  153,  153,  236,  236,
      236,  153,  153,  153,  236,  153,  153,  153,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  153,  186,  186,
      276,  186,  207,  186,  186,  186,  186,  186,  186,  273,
      207,  278,  186,  186,  186,  207,  207,  186,  186,  277,
      283,  207,  284,  286,  287,  172,  290,  288,  172,  207,
      172,  293,  172,  207,  172,  207,  300,  207,  186,  186,

      186,  301,  186,  302,  186,  186,  186,  186,  186,  186,
      172,  172,  207,  186,  186,  186,  297,  294,  186,  186,
      172,  295,  296,  172,  207,  207,  298,  207,  207,  207,
      299,  172,  172,  292,  291,  289,  207,  207,  285,  186,
      139,  139,  153,  153,  153,  172,  153,  153,  172,  172,
      172,  172,  172,  172,  186,  282,  281,  186,  186,  186,
      207,  280,  279,  207,  207,  207,  222,  207,  222,  222,
      222,  222,  235,  235,  235,  235,  235,  235,  248,  207,
      248,  248,  248,  248,  249,  207,  172,  249,  249,  249,
      172,  172,  266,  265,  264,  263,  262,  261,  259,  257,

      207,  255,  207,  251,  250,  246,  244,  172,  242,  172,
      238,  237,  234,  233,  232,  231,  230,  229,  228,  227,
      226,  225,  224,  209,  208,  204,  191,  188,  187,  173,
      169,  123,  155,  154,  150,  149,  148,  147,  146,  143,
      142,  141,  140,  136,  123,  120,  119,  150,  149,  148,
      147,  146,  143,  142,  141,  140,  136,  123,  120,  119,
      303,    9,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,

      303,  303,  303
    } ;

static yyconst short int yy_chk[704] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,

        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,   11,   11,   12,   12,   16,   18,
       31,   20,   19,   37,   20,   31,   18,   16,   19,   20,
       21,   21,   22,   22,   22,   23,   23,   25,   25,   44,
       42,   45,   46,   47,   47,   46,   44,   45,   37,   42,

       46,   48,   48,   48,   49,   49,   51,   51,   21,   57,
       63,   68,   70,   82,   57,   72,   71,   82,   72,   70,
       68,   47,   71,   72,   73,   73,   74,   74,   74,   75,
       75,   77,   77,   84,   81,   63,   81,   83,   85,   83,
       85,   84,   83,   88,  162,   89,  101,  101,  101,  162,
       88,   86,   73,   78,   78,   78,   78,   78,   78,   78,
       86,   78,   78,   78,   87,   95,   97,   78,   78,   78,
       89,   78,   78,   97,   95,   98,   87,   99,  100,  100,
       99,   98,  102,  102,  112,   99,  104,  104,  109,  113,
      109,  113,  112,   78,   80,   80,   80,   80,   80,   80,

       80,  110,   80,   80,   80,  110,  100,  117,   80,   80,
       80,  114,   80,   80,  111,  116,  111,  115,  175,  111,
      114,  175,  116,  118,  118,  131,  131,   80,  174,  115,
      164,  164,  117,  183,   80,  105,  105,  174,  105,  183,
      105,  105,  105,  105,  105,  105,  133,  133,  133,  105,
      105,  105,  176,  176,  105,  166,  166,  166,  178,  197,
      181,  178,  181,  199,  199,  201,  201,  201,  211,  210,
      217,  211,  217,  197,  219,  105,  108,  108,  210,  108,
      219,  108,  108,  108,  108,  108,  108,  212,  212,  235,
      108,  108,  108,  214,  235,  108,  214,  240,  239,  240,

      248,  245,  241,  243,  245,  253,  254,  253,  247,  108,
      239,  241,  247,  243,  248,  254,  108,  165,  165,  165,
      165,  165,  165,  165,  310,  165,  165,  165,  165,  165,
      165,  165,  165,  165,  165,  165,  165,  165,  165,  165,
      165,  165,  165,  165,  165,  165,  165,  165,  165,  165,
      165,  165,  165,  165,  165,  165,  165,  165,  200,  200,
      256,  200,  302,  200,  200,  200,  200,  200,  200,  252,
      256,  260,  200,  200,  200,  260,  258,  200,  200,  258,
      267,  252,  268,  272,  273,  267,  278,  274,  268,  273,
      301,  284,  272,  274,  284,  278,  297,  296,  200,  249,

      249,  298,  249,  299,  249,  249,  249,  249,  249,  249,
      298,  294,  299,  249,  249,  249,  291,  285,  249,  249,
      285,  288,  289,  293,  288,  289,  293,  295,  290,  287,
      295,  286,  283,  281,  280,  277,  276,  275,  271,  249,
      304,  304,  305,  305,  305,  270,  305,  305,  306,  306,
      306,  269,  306,  306,  307,  266,  265,  307,  307,  307,
      308,  262,  261,  308,  308,  308,  309,  259,  309,  309,
      309,  309,  311,  311,  311,  311,  311,  311,  312,  257,
      312,  312,  312,  312,  313,  255,  246,  313,  313,  313,
      244,  242,  234,  232,  230,  228,  227,  226,  218,  216,

      215,  213,  207,  206,  202,  182,  180,  179,  177,  172,
      171,  167,  150,  149,  148,  147,  145,  144,  143,  142,
      141,  138,  134,  107,  106,  103,   96,   94,   92,   79,
       76,   69,   67,   66,   62,   61,   60,   59,   58,   56,
       55,   54,   53,   50,   43,   41,   40,   36,   35,   34,
       33,   32,   30,   29,   28,   27,   24,   17,   15,   13,
        9,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,

      303,  303,  303
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
static int yy_more_flag = 0;
static int yy_more_len = 0;
#define yymore() (yy_more_flag = 1)
#define YY_MORE_ADJ yy_more_len
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "eudc.l"
#define INITIAL 0
#line 3 "eudc.l"

#include "eudc.tab.hpp"
#include <stdlib.h>
void yyerror(char *);
   
#define VT_VAR 0
#define VT_PTR 1

#define YY_NO_UNISTD_H
#define YY_NEVER_INTERACTIVE 1

#define STATE_LC 1
#define STATE_LC2 2

#define STATE_STRING 3

#line 731 "lex.yy.cpp"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 23 "eudc.l"

	/*
	%token IDENTIFIER INTEGER STRING VARTYPE
	%token FUNC FOR WHILE IF ELSE
	%token CONTINUE BREAK RETURN
	
	%token MONIC_INC MONIC_DEC
	%token BINARY_LSF BINARY_RSF
	%token BINARY_LE BINARY_GE BINARY_EQ BINARY_NE
	%token BINARY_LOGICALAND BINARY_LOGICALOR
	%token ADDASSIGN SUBASSIGN MULASSIGN DIVASSIGN RMDASSIGN
	%token ANDASSIGN ORASSIGN  XORASSIGN LSFASSIGN RSFASSIGN
	*/
	
	

	// Ignore blank line & comments
#line 900 "lex.yy.cpp"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_more_len = 0;
		if ( yy_more_flag )
			{
			yy_more_len = yy_c_buf_p - yytext_ptr;
			yy_more_flag = 0;
			}
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 304 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 662 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 40 "eudc.l"
//skip
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 42 "eudc.l"
{}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 43 "eudc.l"
{ BEGIN STATE_LC; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 44 "eudc.l"
{ BEGIN STATE_LC2; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 45 "eudc.l"
{ }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 46 "eudc.l"
{ BEGIN 0; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 47 "eudc.l"
{}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 48 "eudc.l"
{ BEGIN STATE_LC; }
	YY_BREAK
/* Read all known keywords */
case 9:
YY_RULE_SETUP
#line 53 "eudc.l"
{ return IF; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 54 "eudc.l"
{ return ELSE; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 55 "eudc.l"
{ return FOR; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 56 "eudc.l"
{ return WHILE; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 57 "eudc.l"
{ return FUNC; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 58 "eudc.l"
{ return CONTINUE; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 59 "eudc.l"
{ return BREAK; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 60 "eudc.l"
{ return RETURN; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 62 "eudc.l"
{ return MONIC_INC; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 63 "eudc.l"
{ return MONIC_DEC; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 64 "eudc.l"
{ return BINARY_LSF; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 65 "eudc.l"
{ return BINARY_RSF; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 66 "eudc.l"
{ return BINARY_LE; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 67 "eudc.l"
{ return BINARY_GE; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 68 "eudc.l"
{ return BINARY_EQ; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 69 "eudc.l"
{ return BINARY_NE; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 70 "eudc.l"
{ return BINARY_LOGICALAND; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 71 "eudc.l"
{ return BINARY_LOGICALOR; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 72 "eudc.l"
{ return ADDASSIGN; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 73 "eudc.l"
{ return SUBASSIGN; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 74 "eudc.l"
{ return MULASSIGN; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 75 "eudc.l"
{ return DIVASSIGN; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 76 "eudc.l"
{ return RMDASSIGN; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 77 "eudc.l"
{ return ANDASSIGN; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 78 "eudc.l"
{ return ORASSIGN; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 79 "eudc.l"
{ return XORASSIGN; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 80 "eudc.l"
{ return LSFASSIGN; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 81 "eudc.l"
{ return RSFASSIGN; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 84 "eudc.l"
{ yylval = VT_VAR; return VARTYPE; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 85 "eudc.l"
{ yylval = VT_PTR; return VARTYPE; }
	YY_BREAK
/* Read identifiers */
case 39:
YY_RULE_SETUP
#line 89 "eudc.l"
{
		// yylval = GetNameIdentifier(yytext);
		return IDENTIFIER;
	}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 94 "eudc.l"
{
		yylval = strtol(yytext, NULL, 0);
		return INTEGER;
	}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 101 "eudc.l"
BEGIN STATE_STRING; /* no yymore here */
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 102 "eudc.l"
yymore();
	YY_BREAK
case YY_STATE_EOF(STATE_STRING):
#line 103 "eudc.l"
{ yyerror("EOF in string.");       BEGIN 0; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 104 "eudc.l"
{ yyerror("Unterminated string."); BEGIN 0; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 105 "eudc.l"
yymore();
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 106 "eudc.l"
{
		yytext[yyleng-1] = '\0';
		BEGIN 0;
	}
	YY_BREAK
/* anything else will just pass by. */
case 46:
YY_RULE_SETUP
#line 113 "eudc.l"
{ return *yytext; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 114 "eudc.l"
ECHO;
	YY_BREAK
#line 1248 "lex.yy.cpp"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(STATE_LC):
			case YY_STATE_EOF(STATE_LC2):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 304 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 304 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 303);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 114 "eudc.l"

